### ISSUE TITLE
Is is possible to do quality control and parse at the same time?

### ISSUE THREAD

**Issue by soerendip** [kevinkovalchik/RawTools#33]
It seems the commandline arguments for `qc` and `parse` are somewhat mixed. So essentially, one has to run `rawtools parse` and `rawtools qc` as separate commands. Is that correct? I also wonder, for quality control if files are continuously added to the same directory? Would `rawtools` recognise which files it has already processed or would it process all files again. The qc module has no `-f` option only `-d`.

**Comment by kevinkovalchik** [comment]
We are planning to allow parse and qc at the same time. You can actually do
this with the GUI beta. We haven't streamlined it yet, but if you download
that version you can do it. I imagine you will be using the CLI, so just
run RawTools.exe from the GUI release rather than RawToolsGUI.exe. To do
both, use this syntax:
`RawTools.exe all -d [directory] -q [QC directory] {other options from QC
or parse}`
I believe that is how it was set up. The "all" verb is a bit clunky, so
I'll clean up the interface more at some point. Also, if you set up an
analysis in the GUI using g both QC and parse and start it, the command
line arguments will be saved in the log file, so you can check out how to
do it in there if my above suggestion doesn't seem to work. Note the GUI
version is built on 1.4.1, so any bugs that have been fixed since then will
still be there.

For your second question, yes it will only process new files that get
added. So if you run it on 10 files, then add one more to the directory and
run the program again it will only process that one file and add the data
to the QC files.

Kevin
