### ISSUE TITLE
how to input the impurity correction when run the RawTools

### ISSUE THREAD

**Issue by pfangpGlyco** [kevinkovalchik/RawTools#45]
Hello Kevin,
Thanks a lot for developing such a fantastic tool! I have a little problem with TMT6 data analysis using Rawtools. How to do the impurity correction for TMT?
![Capture](https://user-images.githubusercontent.com/35302429/61519851-33b04e80-aa0d-11e9-802f-1b2612018a4d.PNG)

The command line above worked well to output the intensities of reproter ions, how can I do it to do the impurity correction. I found the following message in Rawquant. 

> -c' this will correct for isotopic impurities in the reagents. Input should be a csv file containing an impurity matrix. For an example, try python RawQuant examples -c.

Sorry about that I 'm not a informatics  researcher and sometimes confused with the computer language.  

Thanks very much for your help
Pan Fang

**Comment by kevinkovalchik** [comment]
Hello,

Sorry, this actually is something that isn't available in RawTools, at
least at the moment. It was in RawQuant, but because of time constraints we
didn't implement it in the original RawTools release, and you are actually
the first person to ask about it! So basically we just never got around to
it... I'll work on it and get it into a future release.

I'm going to be transitioning into a new research position over the next
few months, so I probably won't get to this super fast, but I'll work on it!

Kevin

**Comment by pfangpGlyco** [comment]
Hello Kevin, 
Thanks for developing such a great tool. Its very helpful for my glycopeptide quantification. We have developed a automatic data processing tool for quantitative glycopeptides by integrating RawTools into the tool. Please see the BioRxiv link: https://www.biorxiv.org/content/10.1101/2020.05.20.105726v1
Now we have met a problem with impurity correction. Did you already put this into the current release? 

Best regards,
Pan
